[package]
name = "kafka-deduplicator"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
aws-config = { workspace = true }
aws-sdk-s3 = { workspace = true }
axum = { workspace = true }
bincode = { version = "2.0.1", features = ["serde"] }
chrono = { workspace = true }
serve-metrics = { path = "../common/serve_metrics" }
common-types = { path = "../common/types" }
envconfig = { workspace = true }
futures = "0.3"
metrics = { workspace = true }
metrics-exporter-prometheus = { workspace = true }
num_cpus = "1.17.0"
rdkafka = { workspace = true }
rocksdb = "0.23.0"
serde = { workspace = true }
serde_json = "1.0"
time = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
tempfile = "3.8"
uuid = { version = "1.0", features = ["v4"] }
