packages:
    - '.'
    - common/esbuilder
    - common/eslint_rules
    - common/hogvm/typescript
    - common/plugin_transpiler
    - common/storybook
    - common/tailwind
    - cypress
    - ee/frontend
    - frontend
    - playwright
    - plugin-server
    - products/*
    - rust/cyclotron-node

catalog:
    posthog-js: ^1.256.2
    posthog-js-lite: ^3.6.0
