packages:
    - '.'
    - common/esbuilder
    - common/eslint_rules
    - common/hogvm/typescript
    - common/plugin_transpiler
    - common/shared_types
    - common/storybook
    - common/tailwind
    - cypress
    - ee/frontend
    - frontend
    - playwright
    - plugin-server
    - products/*
    - rust/cyclotron-node
