name: Build and cache Docker image test

inputs:
    actions-id-token-request-url:
        required: true
        description: "ACTIONS_ID_TOKEN_REQUEST_URL, issued by GitHub when permission 'id-token' is set to 'write'"
    save:
        required: false
        default: 'false'
        description: Whether to save the image in the Depot ephemeral registry after building it
    aws-access-key:
        required: true
        description: AWS key to log into ECR
    aws-access-secret:
        required: true
        description: AWS secret to log into ECR

outputs:
    tag:
        description: The tag of the image that was built
        value: ${{ steps.emit.outputs.tag }}
    build-id:
        description: The ID of the build
        value: ${{ steps.build.outputs.build-id }}

runs:
    using: 'composite'
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Set up Depot CLI
          uses: depot/setup-action@v1

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
              aws-access-key-id: ${{ inputs.aws-access-key }}
              aws-secret-access-key: ${{ inputs.aws-access-secret }}
              aws-region: us-east-1

        - name: Login to Amazon ECR
          id: aws-ecr
          uses: aws-actions/amazon-ecr-login@v2

        - name: Emit image tag
          id: emit
          shell: bash
          run: echo "tag=posthog/posthog:${{ github.sha }}" >> $GITHUB_OUTPUT

        - name: Build image
          id: build
          uses: depot/build-push-action@v1
          with:
              context: .
              buildx-fallback: false # buildx is so slow it's better to just fail
              tags: ${{ steps.emit.outputs.tag }},${{ steps.aws-ecr.outputs.registry }}/posthog-cloud:${{ github.sha }}
              platforms: linux/amd64,linux/arm64
              build-args: COMMIT_HASH=${{ github.sha }}
              save: ${{ inputs.save }}
          env:
              ACTIONS_ID_TOKEN_REQUEST_URL: ${{ inputs.actions-id-token-request-url }}
