# Generated by Django 4.2.22 on 2025-08-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posthog", "0821_team_session_recording_retention_period"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="session_recording_retention_period",
            field=models.CharField(
                choices=[
                    ("legacy", "Legacy Retention"),
                    ("30d", "30 Days"),
                    ("90d", "90 Days"),
                    ("1y", "1 Year"),
                    ("5y", "5 Years"),
                ],
                default="legacy",
                max_length=6,
            ),
        ),
    ]
