[package]
name = "common-cookieless"
version = "0.0.1"
edition = "2021"

[lints]
workspace = true

[features]
examples = []

[dependencies]
async-trait = { workspace = true }
axum = { workspace = true, optional = true }
base64 = { workspace = true }
chrono = { workspace = true }
chrono-tz = { workspace = true }
common-metrics = { path = "../metrics" }
common-redis = { path = "../redis" }
futures = { workspace = true }
itoa = { workspace = true }
metrics = { workspace = true }
moka = { workspace = true, features = ["sync"] }
public-suffix = "0.1.2"
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
siphasher = "1.0.1"
thiserror = { workspace = true }
tokio = { workspace = true, features = ["sync", "time"] }
url = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }

