[package]
name = "serde-elements"
version = "0.1.0"
edition = "2021"

[lib]
name = "serde_elements"
crate-type = ["cdylib"]

[dependencies]
regex = "^1.11.1"
once_cell = "^1.20.2"
rayon = "^1.10.0"
pyo3 = { version = "0.22.6", features = ["extension-module", "macros"] }
