name: Frontend CI

on:
    workflow_call:

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
    frontend-code-quality:
        name: Code quality checks
        needs: changes
        # kea typegen and typescript:check need some more oomph
        runs-on: depot-ubuntu-24.04-4
        steps:
            # we need at least one thing to run to make sure we include everything for required jobs
            - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

            - name: Install pnpm
              uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4

            - name: Set up Node.js
              uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
              with:
                  node-version: 18.12.1
                  cache: 'pnpm'

            - name: Get pnpm cache directory path
              id: pnpm-cache-dir
              run: echo "PNPM_STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

            - uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4
              id: pnpm-cache
              with:
                  path: ${{ steps.pnpm-cache-dir.outputs.PNPM_STORE_PATH }}
                  key: ${{ runner.os }}-pnpm-cypress-${{ hashFiles('pnpm-lock.yaml') }}
                  restore-keys: ${{ runner.os }}-pnpm-cypress-

            - name: Install package.json dependencies with pnpm
              run: |
                  pnpm --filter=@posthog/playwright... install --frozen-lockfile
                  bin/turbo --filter=@posthog/frontend prepare

            - name: Check formatting with prettier
              run: pnpm --filter=@posthog/frontend prettier:check

            - name: Lint with Stylelint
              run: pnpm --filter=@posthog/frontend lint:css

            - name: Generate logic types and run typescript with strict
              run: pnpm --filter=@posthog/frontend typegen:write && pnpm --filter=@posthog/frontend typescript:check
              env:
                  NODE_OPTIONS: --max-old-space-size=16384

            - name: Lint with ESLint
              run: pnpm --filter=@posthog/frontend lint:js
              env:
                  NODE_OPTIONS: --max-old-space-size=16384

            - name: Check if "schema.json" is up to date
              run: pnpm --filter=@posthog/frontend schema:build:json && git diff --exit-code

            - name: Check if mobile replay "schema.json" is up to date
              run: pnpm --filter=@posthog/ee mobile-replay:schema:build:json && git diff --exit-code

            - name: Check toolbar bundle size
              uses: preactjs/compressed-size-action@946a292cd35bd1088e0d7eb92b69d1a8d5b5d76a # v2
              with:
                  build-script: '--filter=@posthog/frontend build'
                  install-script: 'pnpm --filter=@posthog/frontend... install'
                  compression: 'none'
                  pattern: 'frontend/dist/toolbar.js'
                  # we only care if the toolbar will increase a lot
                  minimum-change-threshold: 1000

    jest:
        runs-on: depot-ubuntu-24.04
        needs: changes
        name: Jest test (${{ matrix.segment }} - ${{ matrix.chunk }})

        strategy:
            # If one test fails, still run the others
            fail-fast: false
            matrix:
                segment: ['FOSS', 'EE']
                chunk: [1, 2, 3]

        steps:
            # we need at least one thing to run to make sure we include everything for required jobs
            - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

            - name: Remove ee
              if: matrix.segment == 'FOSS'
              run: rm -rf ee

            - name: Install pnpm
              uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4

            - name: Set up Node.js
              uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
              with:
                  node-version: 18.12.1
                  cache: pnpm

            - name: Install package.json dependencies with pnpm
              run: pnpm --filter=@posthog/frontend... install --frozen-lockfile

            - name: Test with Jest
              run: bin/turbo run test --filter=@posthog/frontend
              env:
                  NODE_OPTIONS: --max-old-space-size=16384
                  SHARD_INDEX: ${{ matrix.chunk }}
                  SHARD_COUNT: 3

    calculate-running-time:
        name: Calculate running time
        needs: [jest, frontend-code-quality, changes]
        runs-on: depot-ubuntu-24.04
        steps:
            - name: Calculate running time
              run: |
                  echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
                  run_id=${GITHUB_RUN_ID}
                  repo=${GITHUB_REPOSITORY}
                  run_info=$(gh api repos/${repo}/actions/runs/${run_id})
                  echo run_info: ${run_info}
                  # name is the name of the workflow file
                  # run_started_at is the start time of the workflow
                  # we want to get the number of seconds between the start time and now
                  name=$(echo ${run_info} | jq -r '.name')
                  run_url=$(echo ${run_info} | jq -r '.url')
                  run_started_at=$(echo ${run_info} | jq -r '.run_started_at')
                  run_attempt=$(echo ${run_info} | jq -r '.run_attempt')
                  start_seconds=$(date -d "${run_started_at}" +%s)
                  now_seconds=$(date +%s)
                  duration=$((now_seconds-start_seconds))
                  echo running_time_duration_seconds=${duration} >> $GITHUB_ENV
                  echo running_time_run_url=${run_url} >> $GITHUB_ENV
                  echo running_time_run_attempt=${run_attempt} >> $GITHUB_ENV
                  echo running_time_run_id=${run_id} >> $GITHUB_ENV
                  echo running_time_run_started_at=${run_started_at} >> $GITHUB_ENV

            - name: Capture running time to PostHog
              uses: PostHog/posthog-github-action@v0.1
              with:
                  posthog-token: ${{secrets.POSTHOG_API_TOKEN}}
                  event: 'posthog-ci-running-time'
                  properties: '{"runner": "depot", "duration_seconds": ${{ env.running_time_duration_seconds }}, "run_url": "${{ env.running_time_run_url }}", "run_attempt": "${{ env.running_time_run_attempt }}", "run_id": "${{ env.running_time_run_id }}", "run_started_at": "${{ env.running_time_run_started_at }}"}'
