#
# Build and push PostHog and PostHog Cloud container images
#
# - posthog_build: build and push the PostHog container image to DockerHub
#
# - posthog_cloud_build: build the PostHog Cloud container image using
#   as base image the container image from the previous step. The image is
#   then pushed to AWS ECR.
#
name: Container Images CD

on:
    push:
        branches:
            - master
        paths-ignore:
            - 'rust/**'
            - 'livestream/**'
    workflow_dispatch:
        inputs:
            usePosthogRunner:
                type: boolean
                default: false
                description: 'Run mirrored build using self-hosted posthog-runners'

jobs:
    posthog_build_mirrored:
        name: Build and push PostHog (self-hosted runner)
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.usePosthogRunner == 'true'
        runs-on: posthog-runners
        permissions:
            id-token: write
            contents: read
            packages: write

        steps:
            - name: Check out
              uses: actions/checkout@v4
              with:
                  fetch-depth: 2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3
              with:
                  install: true
                  driver-opts: image=moby/buildkit:latest

            - name: Set up QEMU
              uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1

            - name: Login to Amazon ECR
              id: aws-ecr
              uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2

            - name: Login to DockerHub
              uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
              with:
                  username: ${{ secrets.DOCKERHUB_USER }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Login to ghcr.io
              uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
                  logout: false

            - name: Cache Docker layers
              uses: actions/cache@v4
              with:
                  path: /mnt/buildkit-cache
                  key: ${{ runner.os }}-buildx-${{ github.sha }}
                  restore-keys: |
                      ${{ runner.os }}-buildx-

            - name: Build container image
              id: build_mirrored
              uses: docker/build-push-action@v5
              with:
                  push: false
                  tags: |
                      ghcr.io/posthog/posthog:${{ github.sha }}-mirrored
                  platforms: linux/arm64
                  build-args: COMMIT_HASH=${{ github.sha }}
                  cache-from: type=local,src=/buildkit-cache
                  cache-to: type=local,dest=/buildkit-cache,mode=max
