name: Build Nightly CI Image

on:
    schedule:
        # Run nightly at 2 AM UTC
        - cron: '0 2 * * *'
    workflow_dispatch:
        inputs:
            force_rebuild:
                description: 'Force rebuild without cache'
                required: false
                default: false
                type: boolean

jobs:
    build-ci-image:
        name: Build CI Image
        runs-on: depot-ubuntu-latest-4
        timeout-minutes: 30
        permissions:
            # Allow issuing OIDC tokens for this workflow run
            id-token: write
            contents: read
        outputs:
            build-id: ${{ steps.build.outputs.build-id }}
            tag: ${{ steps.build.outputs.tag }}

        steps:
            - name: Check out
              uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
              with:
                  ref: master

            - name: Set up Depot CLI
              uses: depot/setup-action@b0b1ea4f69e92ebf5dea3f8713a1b0c37b2126a5 # v1.6.0

            - name: Build and save CI image in Depot
              id: build
              uses: depot/build-push-action@636daae76684e38c301daa0c5eca1c095b24e780 # v1
              with:
                  context: .
                  file: ./Dockerfile.ci
                  save: true # Save to Depot's ephemeral registry
                  tags: posthog/ci:nightly
                  platforms: linux/amd64,linux/arm64
                  project: 'm736dg11vv'
                  build-args: |
                      COMMIT_HASH=${{ github.sha }}
                  no-cache: ${{ github.event.inputs.force_rebuild == 'true' }}
              env:
                  ACTIONS_ID_TOKEN_REQUEST_URL: ${{ env.ACTIONS_ID_TOKEN_REQUEST_URL }}
