name: Build and deploy node container image

on:
    workflow_dispatch:
    push:
        paths:
            - 'plugin-server/**'
            - 'common/hogvm/**'
            - 'common/plugin_transpiler/**'
            - '.github/workflows/node-docker-build.yml'
        branches:
            - 'master'

jobs:
    build:
        name: build node container image
        runs-on: depot-ubuntu-22.04
        permissions:
            id-token: write # allow issuing OIDC tokens for this workflow run
            contents: read # allow reading the repo contents
            packages: write # allow push to ghcr.io

        outputs:
            digest: ${{ steps.digest.outputs.digest }}

        steps:
            - name: Check Out Repo
              uses: actions/checkout@v3

            - name: Set up Depot CLI
              uses: depot/setup-action@v1

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
              with:
                  image: tonistiigi/binfmt:latest
                  platforms: all

            - name: Login to ghcr.io
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
                  logout: false

            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ghcr.io/posthog/posthog/node
                  tags: |
                      type=ref,event=pr
                      type=ref,event=branch
                      type=semver,pattern={{version}}
                      type=semver,pattern={{major}}.{{minor}}
                      type=sha

            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v2

            - name: Build and push image
              id: docker_build
              uses: depot/build-push-action@v1
              with:
                  project: ${{ matrix.project }}
                  context: .
                  file: plugin-server/Dockerfile
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  platforms: linux/arm64,linux/amd64

            - name: Container image digest
              id: digest
              run: |
                  echo ${{ steps.docker_build.outputs.digest }}
                  echo "digest=${{ steps.docker_build.outputs.digest }}" >> $GITHUB_OUTPUT
                  cat $GITHUB_OUTPUT

    deploy:
        name: deploy ${{ matrix.release }}
        runs-on: ubuntu-24.04
        needs: build
        if: github.ref == 'refs/heads/master'
        steps:
            - name: get deployer token
              id: deployer
              uses: getsentry/action-github-app-token@v3
              with:
                  app_id: ${{ secrets.DEPLOYER_APP_ID }}
                  private_key: ${{ secrets.DEPLOYER_APP_PRIVATE_KEY }}

            - name: trigger nodedeployment
              uses: peter-evans/repository-dispatch@v3
              with:
                  token: ${{ steps.deployer.outputs.token }}
                  repository: PostHog/charts
                  event-type: commit_state_update
                  client-payload: |
                      {
                        "values": ${{ toJson(matrix.values) }},
                        "release": "${{ matrix.release }}",
                        "commit": ${{ toJson(github.event.head_commit) }},
                        "repository": ${{ toJson(github.repository) }},
                        "labels": [],
                        "timestamp": "${{ github.event.head_commit.timestamp }}"
                      }
